name: healthy
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5

  flutter_blue: ^0.8.0
  permission_handler: ^10.2.0

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.15
  image_picker_for_web: ^3.0.0
  image_picker: ^1.0.2
  awesome_dialog: ^3.2.1
  rive: ^0.13.4
  url_launcher: ^6.0.20
  flutter_gradient_colors: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  build_runner: ^2.0.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/heart.png
    - images/coeur.png
    - images/check.png
    - images/back.jpg
